### PR TITLE
Test Class TreeModel

### PR DESCRIPTION
**Pull request by MarkusHackspacher**
Test for the class TreeModel. The purpose of the exercise was to test the move_vertical call. But I have not managed to create meaningful queries. Maybe could you help?

### CODE REVIEW

**Comment by Tamriel** [comment]
I am sorry I found no time to review your pull request.

**Comment by MarkusHackspacher** [comment]
I reopen it. Maybe you have time for a look.

**Comment by Tamriel** [comment]
To be honest, even though I use TreeNote daily, I won't invest time in this codebase anymore, because I am already working on its successor - which is written in a different language.

**Comment by JonasDralle** [comment]
sounds like a reason to fork

**Comment by Tamriel** [comment]
Nothing new, I already wrote about this in the Readme file ;-)
If anybody wants to collaborate, I can add him to the TreeNote team, so he can commit.

**Comment by MarkusHackspacher** [comment]
Yes, you can add me.

**Pull request merged**
